# Generated by Django 3.0.8 on 2020-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enum_choice_field', '0002_auto_20200703_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
